### PR TITLE
What the actual fuck dude

### PR DESCRIPTION
**Pull request by SteamingMutt**
I don't even

### CODE REVIEW

**Comment by TheKill69** [comment]
:+1:

**Comment by kjuy86t** [comment]
i have it on her because i use github to deploy to heroku.

**Comment by Rekkisomo** [comment]
its called: SSH. Learn it, use it, Read the fucking docs on Heroku.

**Comment by Rekkisomo** [comment]
Also, if you have no idea wtf you're doing with this bot/javascript, stop trying. I've gone through your commits and just... ugh

**Comment by Rekkisomo** [comment]
Otherwise, buy a Github membership and make this git private.

**Comment by Rekkisomo** [comment]
Because really, anyone who views this git can use your bot's account now.

**Pull request closed without merging**
